apiVersion: apps/v1
kind: Deployment
metadata:
  name: javapod
  #namespace: test-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
        - name: javapod
          image: doh1/java-web-app:1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: javasvc
  #namespace: test-ns
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: javaapp
