apiVersion: v1
kind: ReplicationController
metadata:
  name: mavenwebapp
spec:
  template:
    metadata:
      labels:
        app: mavenwebapp
    spec:
      containers:
        - name: mavenwebapp
          image: doh1/maven-web-app:12
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenwebappsvc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: mavenwebapp
