apiVersion: apps/v1
kind: Deployment
metadata:
  name: javadeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appjava
  template:
    metadata:
      labels:
        app: appjava
    spec:
      containers:
        - name: javadeployment
          image: doh1/java-web-app:1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 700m
              memory: 448Mi
            limits:
              cpu: 900m
              memory: 712Mi
          livenessProbe:
            httpGet:
              path: /java-web-app
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /java-web-app
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 5
            timeoutSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: javasvc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: appjava
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingressrul
spec:
  ingressClassName: nginx
  rules:
    - host: javaapp.doh1cloud.click
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: javasvc
                port:
                  number: 80
