apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test-ns
  name: mavenwebapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
        - name: mavencontainer
          image: doh1/maven-web-app:1
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavensvp
  namespace: test-ns
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: maven
